---
- name: Basic Facts
  set_fact:
    system_config: "{{ system_configs[ansible_distribution] }}"
    arch: "{{ arch_folders[ansible_architecture] }}"
    oracle_tmp_install: /tmp
    local_debug_verbosity: "{{ custom_debug_verbosity | default(2) }}"

- name: Debug system_configs
  debug:
    var: system_configs
    verbosity: "{{ local_debug_verbosity }}"

- name: Debug ansible_distribution
  debug:
    var: ansible_distribution
    verbosity: "{{ local_debug_verbosity }}"

- name: Ensure variables
  fail:
    msg: Variable '{{ item }}' was not properly defined
  when:
    - item is undefined or item | length == 0
  with_items:
    - system_config
    - arch
    - pkg_rpm

- name: Fallback for version
  set_fact:
    version: "{{ system_config.version }}"
  when: version is undefined or version | length == 0

- name: Version Config
  set_fact:
    version_cfg: "{{ version_configs[system_config.system][version] }}"

- name: Debug version_cfg
  debug:
    var: version_cfg
    verbosity: "{{ local_debug_verbosity }}"

- name: Prep Filenames
  set_fact:
    filenames: []

- name: Set Filenames
  set_fact:
    # filenames: "{{ filenames }} + [ 'instantclient-{{ item }}-{{ system_config.system }}.{{ arch }}-{{ version_cfg.rpm_suffix }}.rpm' ]"
    filenames: "{{ filenames }} + [ 'oracle-instantclient{{ version_cfg.ver_suffix }}-{{ item }}-{{ version_cfg.rpm_suffix }}.{{ ansible_architecture }}.rpm' ]"
  with_items: "{{ packages }}"

# - name: Set Include Type when local
#   set_fact:
#     incl_type: local
#   when: inventory_hostname == 'localhost'

- name: Ensure packages are installed
  yum:
    # name: ["zip", "unzip", "gzip", "libaio1"]
    name: ["libaio"]
    state: present
  become: false
  when: (system_config.system == "linux" and ansible_distribution == "CentOS")

- name: More facts
  set_fact:
    libtype: "{{ lib_types[system_config.system] }}"
    lib_path: "{{ lib_paths[system_config.system] }}"
    # client_path: "{{ oracle_clients | regex_replace( '/$', '' ) }}/{{ system_config.system }}/{{ arch }}"
    # unzip_path: "instantclient_{{ version_cfg.lib }}"

# - name: Client Path Status
#   stat:
#     path: "{{ client_path }}"
#   connection: local
#   register: p

# - name: Fail when the client package directory is not valid
#   fail:
#     msg: "client_path does not exist. Make sure oracle_clients is set properly."
#   when: (p.stat.exists is defined and not p.stat.exists)

# - name: Fail when the path exists and is a directory
#   fail:
#     msg: "Path exists and is a directory"
#   when: (p.stat.isdir is undefined or not p.stat.isdir)

- name: Fail when not CentOS
  fail:
    msg: "System is not CentOS"
  when: not ansible_distribution == "CentOS"

- name: Display debug filenames
  debug:
    var: filenames
    verbosity: "{{ local_debug_verbosity }}"

- include_tasks: client.{{ incl_type }}.rpm.yml
