---

#  - fail: msg="Please define local client_pkg_dir variable"
#    when: client_pkg_dir == ""

  - set_fact:
      gather_facts: "{{not is_local_host is defined and is_local_host == true}}"
      dist: "{{ dist_folders[ansible_distribution] }}"
      arch: "{{ arch_folders[ansible_architecture] }}"

  - debug: var=gather_facts
  - debug: var=dist
  - debug: var=arch


  - set_fact:
      cp_type: "remote"
    when: gather_facts == true

  - set_fact:
      cp_type: "local"
    when: gather_facts == false

  - debug: var=cp_type

  - name: Ensure packages are installed
    apt:
      name: "{{ item }}"
      state: installed
    become: true
    with_items:
      - zip
      - unzip
      - gzip
      - libaio1
    when: client_pkg_dir != "" and dist == "linux"

  - set_fact:
      driver: "{{ driver_types[dist] }}"

  - fail: msg="Couldn't do the dist var"
    when: not dist is defined or dist == ""

  - fail: msg="Couldn't do the arch var"
    when: not arch is defined or arch == ""

  - set_fact:
      client_path: "{{ client_pkg_dir }}/{{ dist }}/{{ arch }}"

  - local_action: stat path={{ client_path }}
    register: p

  - debug: var=client_path
  - debug: var=p

  - fail: msg="Path does not exist"
    when: client_pkg_dir != "" and (p.stat.exists is defined and p.stat.exists|bool == false)

  - fail: msg="Path exists and is a directory"
    when: client_pkg_dir != "" and (not p.stat.isdir is defined or p.stat.isdir|bool == false)

  - name: Configure Wordpress Apache
    include: ./client.{{ cp_type }}.yml


#    nano /tmp/ocicheck.sh
#    chmod a+x /tmp/ocicheck.sh
#    sudo /tmp/ocicheck.sh
